# Site Configuration
theme: default
lang: "en"
plugins: []
google_analytics_id:

title: "Sweet Treats by Therese"
# Pointing to the newly renamed logo!
avatar: "./logo.png"
name: "Sweet Treats by Therese"
tagline: >-
  Custom Baking & Elegant Desserts<br>Email: akkyou29@gmail.com | Phone: (484) 951-5364

links:
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://instagram.com/streats.29"
      alt: "Instagram Profile"
      title: "Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-facebook"
      text: "Facebook"
      url: "https://facebook.com/sweettreatsbytherese"
      alt: "Facebook Page"
      title: "Facebook"
      target: "_blank"
  - link:
      icon: "fa-solid fa-dollar-sign"
      text: "Pay with CashApp"
      url: "https://cash.app/$sweettreatsbytherese"
      alt: "CashApp Link"
      title: "CashApp"
      target: "_blank"
  - link:
      icon: "fa-brands fa-vimeo-v"
      text: "Pay with Venmo"
      url: "https://venmo.com/therese-younes"
      alt: "Venmo Link"
      title: "Venmo"
      target: "_blank"

socials:
  - social:
     #add phone  number
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:akkyou29@gmail.com"
      title: "Email"
      alt: "Email"
      target: "_blank"

footer: >
  Specializing in custom cakes, cupcakes, and elegant treats for your special moments.
copyright: >
  © 2026 Sweet Treats by Therese. All rights reserved.
